# Packages
brew "bat"
brew "curl"
brew "doggo"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "imagemagick"
brew "lazygit"
brew "mas"
brew "mise"
brew "ripgrep"
brew "starship"
brew "stow"
brew "trash"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"

# Apps
cask "cleanshot"
cask "figma"
cask "firefox@developer-edition"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "google-chrome"
# cask "notion"
cask "notion-calendar"
cask "pixelsnap"
# cask "raycast"
cask "slack"
cask "visual-studio-code"

# Apps from the App Store
mas "Harvest", id: 506189836