#!/bin/bash
set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

# ai-context — shared personal instructions for AI coding agents.
# This phase:
#   1. Clones/updates the ai-context repo (the canonical base AGENTS.md).
#   2. Bootstraps the private local overlay from the shipped example.
#   3. Wires the base + overlay into Claude Code (via @imports) and Codex.
#
# Codex has no import syntax, so its AGENTS.md is GENERATED by concatenating
# base + overlay. Do not hand-edit ~/.codex/AGENTS.md; edit the sources and
# re-run. This phase must run BEFORE the rtk phase: rtk appends its own
# @RTK.md ref to ~/.codex/AGENTS.md, and regenerating here would drop it.
# A full setup.sh run self-heals because rtk runs afterwards.

# Skills/instructions only matter if an agent is installed. Gate like rtk.
if ! command_exists claude && ! command_exists codex; then
	warn "Neither claude nor codex found on PATH. Skipping ai-context."
	warn "Install an agent, then re-run: ~/.dotfiles/scripts/install-ai-context.sh"
	exit 0
fi

REPO_URL="https://github.com/benderham/ai-context"
CTX_DIR="$HOME/.config/ai-context"
REPO_DIR="$CTX_DIR/repo"
BASE="$REPO_DIR/AGENTS.md"
EXAMPLE="$REPO_DIR/local.md.example"
LOCAL="$CTX_DIR/local.md"

# -- Clone / update the repo ---------------------------------------------------
mkdir -p "$CTX_DIR"
if [ ! -d "$REPO_DIR/.git" ]; then
	info "Cloning ai-context..."
	git clone "$REPO_URL" "$REPO_DIR"
else
	info "Updating ai-context..."
	git -C "$REPO_DIR" pull --ff-only || warn "ai-context pull failed; using existing checkout."
fi

if [ ! -f "$BASE" ]; then
	error "Base AGENTS.md not found at $BASE. Aborting ai-context wiring."
	exit 1
fi

# -- Bootstrap the private overlay ---------------------------------------------
# The real overlay is private and never committed. Seed it from the example
# once, then leave it alone so local edits survive re-runs.
if [ ! -e "$LOCAL" ]; then
	if [ -f "$EXAMPLE" ]; then
		cp "$EXAMPLE" "$LOCAL"
		warn "Seeded $LOCAL from example. Edit it with your identity and job context."
	else
		warn "No local.md.example in repo; skipping overlay bootstrap."
	fi
fi

# -- Claude Code ---------------------------------------------------------------
# Claude concatenates its own files and supports @imports, so CLAUDE.md stays a
# thin importer. Append missing import lines only; never clobber existing content.
if command_exists claude; then
	info "Wiring ai-context into Claude Code..."
	mkdir -p "$HOME/.claude"
	CLAUDE_MD="$HOME/.claude/CLAUDE.md"
	touch "$CLAUDE_MD"
	for import in "@$BASE" "@$LOCAL"; do
		if ! grep -qxF "$import" "$CLAUDE_MD"; then
			printf '%s\n' "$import" >> "$CLAUDE_MD"
			info "Added import to CLAUDE.md: $import"
		fi
	done
else
	info "Claude Code not installed — skipping Claude wiring."
fi

# -- Codex ---------------------------------------------------------------------
# No import syntax: generate ~/.codex/AGENTS.md by concatenating base + overlay.
if command_exists codex; then
	info "Wiring ai-context into Codex..."
	mkdir -p "$HOME/.codex"
	CODEX_MD="$HOME/.codex/AGENTS.md"
	# Back up a pre-existing real file once before we start generating it.
	if [ -e "$CODEX_MD" ] && [ ! -L "$CODEX_MD" ] && [ ! -e "$CODEX_MD.bak" ]; then
		info "Backing up existing AGENTS.md -> AGENTS.md.bak"
		cp "$CODEX_MD" "$CODEX_MD.bak"
	fi
	{
		cat "$BASE"
		[ -f "$LOCAL" ] && { echo; cat "$LOCAL"; }
	} > "$CODEX_MD"
	info "Generated $CODEX_MD (base + overlay)."
else
	info "Codex not installed — skipping Codex wiring."
fi

success "ai-context setup complete."
