#!/bin/bash
set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

# ai-context — shared personal instructions for AI coding agents.
# This phase:
#   1. Clones/updates the ai-context repo (portable base + personal supplement).
#   2. Bootstraps the private local overlay from the shipped example.
#   3. Wires the layered context into Claude Code and Codex.
#
# Layering per machine:
#   - Every machine gets the base AGENTS.md.
#   - Non-work machines also get personal.md.
#   - Each machine gets its own private local.md overlay.
#   - Work machines get the base only; work context is handled manually.
# A machine is "work" when the git identity phase has written ~/.gitconfig-machine.
#
# Claude Code supports @imports, so CLAUDE.md carries a managed block of import
# lines (rewritten each run, so a personal->work switch drops the personal import;
# content outside the block is preserved). Codex has no import syntax, so its
# AGENTS.md is GENERATED by concatenating the sources. Do not hand-edit it.
#
# Run BEFORE the rtk phase: rtk appends its own @RTK.md ref to ~/.codex/AGENTS.md,
# and regenerating here would drop it. A full setup.sh run self-heals.

if ! command_exists claude && ! command_exists codex; then
	warn "Neither claude nor codex found on PATH. Skipping ai-context."
	warn "Install an agent, then re-run: ~/.dotfiles/scripts/install-ai-context.sh"
	exit 0
fi

REPO_URL="https://github.com/benderham/ai-context"
CTX_DIR="$HOME/.config/ai-context"
REPO_DIR="$CTX_DIR/repo"
BASE="$REPO_DIR/AGENTS.md"
PERSONAL="$REPO_DIR/personal.md"
EXAMPLE="$REPO_DIR/local.md.example"
LOCAL="$CTX_DIR/local.md"

BLOCK_BEGIN="# >>> ai-context (managed) >>>"
BLOCK_END="# <<< ai-context (managed) <<<"

# -- Clone / update the repo ---------------------------------------------------
mkdir -p "$CTX_DIR"
if [ ! -d "$REPO_DIR/.git" ]; then
	info "Cloning ai-context..."
	# Private repo: on a fresh machine there may be no GitHub credential yet.
	# Skip gracefully with a hint instead of aborting the whole setup run.
	if ! git clone "$REPO_URL" "$REPO_DIR"; then
		warn "Could not clone ai-context. If it is private, authenticate to GitHub first"
		warn "(SSH via 1Password, or 'gh auth login'), then re-run: ~/.dotfiles/scripts/install-ai-context.sh"
		exit 0
	fi
else
	info "Updating ai-context..."
	git -C "$REPO_DIR" pull --ff-only || warn "ai-context pull failed; using existing checkout."
fi

if [ ! -f "$BASE" ]; then
	error "Base AGENTS.md not found at $BASE. Aborting ai-context wiring."
	exit 1
fi

# -- Bootstrap the private overlay ---------------------------------------------
# Seed once from the example, then leave it so local edits survive re-runs.
if [ ! -e "$LOCAL" ]; then
	if [ -f "$EXAMPLE" ]; then
		cp "$EXAMPLE" "$LOCAL"
		warn "Seeded $LOCAL from example. Edit it with your machine specifics."
	else
		warn "No local.md.example in repo; skipping overlay bootstrap."
	fi
fi

# -- Resolve the ordered context sources for this machine ----------------------
# Work machine = the git identity phase wrote ~/.gitconfig-machine.
sources=("$BASE")
if [ ! -f "$HOME/.gitconfig-machine" ] && [ -f "$PERSONAL" ]; then
	sources+=("$PERSONAL")
	info "Non-work machine: including personal.md."
else
	info "Work machine (or no personal.md): base only."
fi
[ -f "$LOCAL" ] && sources+=("$LOCAL")

# -- Claude Code ---------------------------------------------------------------
# Rewrite a managed block of @imports; preserve everything else in CLAUDE.md.
if command_exists claude; then
	info "Wiring ai-context into Claude Code..."
	mkdir -p "$HOME/.claude"
	CLAUDE_MD="$HOME/.claude/CLAUDE.md"
	touch "$CLAUDE_MD"
	kept="$(awk -v b="$BLOCK_BEGIN" -v e="$BLOCK_END" '
		$0==b {skip=1} skip && $0==e {skip=0; next} !skip {print}
	' "$CLAUDE_MD")"
	{
		[ -n "$kept" ] && printf '%s\n' "$kept"
		printf '%s\n' "$BLOCK_BEGIN"
		for src in "${sources[@]}"; do printf '@%s\n' "$src"; done
		printf '%s\n' "$BLOCK_END"
	} > "$CLAUDE_MD"
	info "Updated managed import block in $CLAUDE_MD (${#sources[@]} sources)."
else
	info "Claude Code not installed — skipping Claude wiring."
fi

# -- Codex ---------------------------------------------------------------------
# No import syntax: generate ~/.codex/AGENTS.md by concatenating the sources.
if command_exists codex; then
	info "Wiring ai-context into Codex..."
	mkdir -p "$HOME/.codex"
	CODEX_MD="$HOME/.codex/AGENTS.md"
	if [ -e "$CODEX_MD" ] && [ ! -L "$CODEX_MD" ] && [ ! -e "$CODEX_MD.bak" ]; then
		info "Backing up existing AGENTS.md -> AGENTS.md.bak"
		cp "$CODEX_MD" "$CODEX_MD.bak"
	fi
	: > "$CODEX_MD"
	for src in "${sources[@]}"; do
		cat "$src" >> "$CODEX_MD"
		echo >> "$CODEX_MD"
	done
	info "Generated $CODEX_MD (${#sources[@]} sources)."
else
	info "Codex not installed — skipping Codex wiring."
fi

success "ai-context setup complete."
